version: '3'

services:
#   backend: 
#     build: ./
#     restart: always
#     ports:
#       - "8888:8088"
#     depends_on:
#       - mongo
#     environment:
#       # MONGO_USER: mdbuser
#       # MONGO_PASSWORD: password
#       MONGO_URL: mongodb://mongo:27017/

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: mdbuser
    #   MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081 
    # environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: mdbuser
      # ME_CONFIG_MONGODB_ADMINPASSWORD: password
      # ME_CONFIG_MONGODB_URL: ${MONGO_URL}
    depends_on:
      - mongo
  es01:
    image: elasticsearch:8.5.2
    ports:
      - 9200:9200
    restart: always
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g
      - xpack.security.enabled=false
      # - node.name=es01
      # - cluster.name=docker-cluster
      # - cluster.initial_master_nodes=es01,es02,es03
      # - discovery.seed_hosts=es02,es03
      # - ELASTIC_PASSWORD=123456
      # - bootstrap.memory_lock=true
      # - xpack.security.enabled=false
      # - xpack.security.http.ssl.enabled=false
      # - xpack.security.http.ssl.key=certs/es01/es01.key
      # - xpack.security.http.ssl.certificate=certs/es01/es01.crt
      # - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      # - xpack.security.http.ssl.verification_mode=certificate
      # - xpack.security.transport.ssl.enabled=false
      # - xpack.security.transport.ssl.key=certs/es01/es01.key
      # - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
      # - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      # - xpack.security.transport.ssl.verification_mode=certificate
      # - xpack.license.self_generated.type=basic
    mem_limit: 1073741824
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    # volumes:
    #   - elasticsearch:/data/es
    
  # nginx:
  #   image: nginx:alpine

volumes:
  mongodb_data:
  # elasticsearch: