// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ArticleInput struct {
	ID          string `json:"id"`
	URL         string `json:"url"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Date        int    `json:"date"`
}
